pipeline:
  build-branch:
    image: plugins/docker
    repo: scienta/${DRONE_REPO_NAME}
    dockerfile: Dockerfile
    context: .
    auto_tag: false
    tags: "branch-${DRONE_BRANCH}"
    secrets: [ docker_username, docker_password ]
    when:
      event: [push]

  #http://plugins.drone.io/drone-plugins/drone-docker/
  build-tag:
    image: plugins/docker
    repo: scienta/${DRONE_REPO_NAME}
    dockerfile: Dockerfile
    context: .
    auto_tag: false
    tags: "${DRONE_TAG}"
    secrets: [ docker_username, docker_password ]
    when:
      event: tag
